name: Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, pypy3]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - os: windows-latest
            python-version: pypy3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: pip install .[test]

      - name: Run tests
        run: true
      #   run: make ci-test

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     fail_ci_if_error: true

  dev-releases:
    name: Publish TestPyPI Releases
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Fetch tag history
        run: git fetch --prune --unshallow --tags

      - name: Prepare build dependencies
        run: pip install -U pip setuptools pep517 twine

      - name: Set test-release-specific release name
        run: sed -i 's/"py-fast-trie"/"py-fast-trie-mischif"/' setup.py

      - name: Build packages
        run: make build

  #     - name: Check packages
  #       run: twine check dist/

  #     - name: Publish test packages
  #       uses: pypa/gh-action-pypi-publish@v1
  #       with:
  #         user: __token__
  #         password: ${{ secrets.test_pypi_password }}
  #         repository_url: https://test.pypi.org/legacy/

  #     - name: Publish main packages
  #       if: startsWith(github.event.ref, 'refs/tags')
  #       uses: pypa/gh-action-pypi-publish@master
  #       with:
  #         user: __token__
  #         password: ${{ secrets.pypi_password }}
