name: CI

on:
	push:
		branches: [master]
	pull_request:
		branches: [master]

jobs:
	tests:
		name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
		runs-on: ${{ matrix.os }}

		strategy:
			matrix:
				python-version: [2.7, pypy2, 3.6, 3.7, 3.8, pypy3]
				os: [ubuntu-latest, windows-latest]

		steps:
			- uses: "actions/checkout@v2"
			- uses: "actions/setup-python@v2"
				with:
					python-version: "${{ matrix.python-version }}"

			- name: "Install dependencies"
				run: pip install .[test]

			- name: "Run tests for ${{ matrix.python-version }}"
				if: runner.os == "Linux"
				run: make ci-test

			- name: "Run tests for ${{ matrix.python-version }}"
				if: runner.os == "Windows"
				run: nmake ci-test

			- name: "Upload coverage to Codecov"
				uses: "codecov/codecov-action@v1"
				with:
					fail_ci_if_error: true
